alias reload!='. ~/.zshrc'
alias v='vim'
alias zrc='~/.dotfiles/zsh/'
alias eclimd='eclimd -Dosgi.instance.area.default=@user.home/Java &'
alias zr='vim ~/.zshrc'
alias za='vim ~/.dotfiles/zsh/aliases.zsh'
alias vr='vim ~/.vimrc'
alias lt='ls -lAhtr'
alias lz='ls -lAS'
